STUDENT PERFORMANCE DATA SET

In [34]:
# 1. Import Pandas and NumPy libraries..
import numpy as np
import pandas as pd

In [ ]:
# 2. Load the CSV file into a DataFrame named df.
df = pd.read_csv("student_performance_dataset.csv")
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,unknown,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,unknown,not recorded,NaN
2,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,Unknown,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [39]:
# 3. Display the first 10 and last 5 rows.
df.head(10)

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,unknown,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,unknown,not recorded,NaN
2,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
5,S002,Pooja Kumari,m,10th,Maths,62,3.5,80,jaipur,N,2026-13-40,-
6,S062,Anjali Jain,MALE,12,Mathematics,NaN,three,72,Jodhpur,no,2026-13-40,Excellent
7,S026,Isha Agarwal,f,Ten,Computer,105,3.5,101,Unknown,Yes,not recorded,late submission
8,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
9,S103,Aarav Sharma,m,10th,math,95,2.5,101,Jodhpur,No,2026-09-15,NaN

In [41]:
df.tail(5)

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,Unknown,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [44]:
# 4. Find the total number of rows and columns.
df.shape

(123, 12)

In [46]:
df.columns

Index(['Student_ID', 'Student Name', 'Gender', 'Class', 'Subject',
       'Attendance_%', 'Study_Hours_Per_Day', 'Exam_Score', 'City',
       'Parent_Contacted', 'Exam_Date', 'Remarks'],
      dtype='str')

In [48]:
# 5. Display all column names and their data types.
df.dtypes

Student_ID             str
Student Name           str
Gender                 str
Class                  str
Subject                str
Attendance_%           str
Study_Hours_Per_Day    str
Exam_Score             str
City                   str
Parent_Contacted       str
Exam_Date              str
Remarks                str
dtype: object

In [52]:
# 6. Check the DataFrame information using info() and summary statistics using describe().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           123 non-null    str
 1   Student Name         123 non-null    str
 2   Gender               115 non-null    str
 3   Class                117 non-null    str
 4   Subject              115 non-null    str
 5   Attendance_%         99 non-null     str
 6   Study_Hours_Per_Day  113 non-null    str
 7   Exam_Score           115 non-null    str
 8   City                 113 non-null    str
 9   Parent_Contacted     107 non-null    str
 10  Exam_Date            102 non-null    str
 11  Remarks              93 non-null     str
dtypes: str(12)
memory usage: 11.7 KB

In [53]:
df.describe()

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
count,123,123,115,117,115,99,113,115,113,107,102,93
unique,74,15,9,9,9,10,11,11,9,7,5,7
top,S092,Aarav Sharma,Unknown,10th,Maths,105,-2,88,Jodhpur,Yes,2026-13-40,good
freq,6,11,20,19,21,14,15,16,21,22,27,19

PART 2

In [61]:
# 1. Count missing values in each column.
df.isnull().sum()

Student_ID              0
Student Name            0
Gender                  8
Class                   6
Subject                 8
Attendance_%           24
Study_Hours_Per_Day    10
Exam_Score              8
City                   10
Parent_Contacted       16
Exam_Date              21
Remarks                30
dtype: int64

In [62]:
# 2. Calculate the percentage of missing values in each column.
df.isnull().mean()*100

Student_ID              0.000000
Student Name            0.000000
Gender                  6.504065
Class                   4.878049
Subject                 6.504065
Attendance_%           19.512195
Study_Hours_Per_Day     8.130081
Exam_Score              6.504065
City                    8.130081
Parent_Contacted       13.008130
Exam_Date              17.073171
Remarks                24.390244
dtype: float64

In [63]:
# 3. Count the exact duplicate rows.
df.duplicated().sum()

np.int64(3)

In [ ]:
# 4. Display all duplicate rows without deleting them.
df[df.duplicated(keep = False)]

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
2,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
8,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
15,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent
120,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [68]:
# 5. Find the number of unique values in every column.
df.nunique()

Student_ID             74
Student Name           15
Gender                  9
Class                   9
Subject                 9
Attendance_%           10
Study_Hours_Per_Day    11
Exam_Score             11
City                    9
Parent_Contacted        7
Exam_Date               5
Remarks                 7
dtype: int64

In [72]:
# 6. Display unique values of Gender, Class, Subject and City.
df['Gender'].unique()

<StringArray>
['MALE', ' m ', 'Unknown', ' f ', 'Male', 'Female', 'female', nan, 'F', 'M']
Length: 10, dtype: str

In [75]:
df['Class'].unique()

<StringArray>
[nan, '10th', '12', 'XI', '12th', 'Ten', 'Class 10', '11', 'Class 12', '10']
Length: 10, dtype: str

In [77]:
df['Subject'].unique()

<StringArray>
[         'SCIENCE',          'English', 'Computer Science',
            'Maths',      'Mathematics',         'Computer',
          'english',             'math',          'Science',
                nan]
Length: 10, dtype: str

In [79]:
df['City'].unique()

<StringArray>
[       nan,  'Jodhpur', 'Jodhpur ', ' jaipur ',  'Unknown',    'Delhi',
    'sikar',    'Sikar',   'Jaipur',    'SIKAR']
Length: 10, dtype: str

In [ ]:
# second method
for col in ["Gender", "Class", "Subject", "City"]:
    print("\n", col)
    print(df[col].unique())

 Gender
<StringArray>
['MALE', ' m ', 'Unknown', ' f ', 'Male', 'Female', 'female', nan, 'F', 'M']
Length: 10, dtype: str

 Class
<StringArray>
[nan, '10th', '12', 'XI', '12th', 'Ten', 'Class 10', '11', 'Class 12', '10']
Length: 10, dtype: str

 Subject
<StringArray>
[         'SCIENCE',          'English', 'Computer Science',
            'Maths',      'Mathematics',         'Computer',
          'english',             'math',          'Science',
                nan]
Length: 10, dtype: str

 City
<StringArray>
[       nan,  'Jodhpur', 'Jodhpur ', ' jaipur ',  'Unknown',    'Delhi',
    'sikar',    'Sikar',   'Jaipur',    'SIKAR']
Length: 10, dtype: str

In [82]:
# # 7. Identify columns containing inconsistent text values or invalid data.
# print(df["Gender"].value_counts(dropna=False))
# print(df["Subject"].value_counts(dropna=False))
# print(df["City"].value_counts(dropna=False))

# print("Invalid attendance:")
# print(df[~df["Attendance_%"].astype(str).str.strip()
#          .str.rstrip("%").pipe(pd.to_numeric, errors="coerce")
#          .between(0, 100)])

# print("Invalid exam scores:")
# scores = pd.to_numeric(df["Exam_Score"], errors="coerce")
# print(df[scores.notna() & ~scores.between(0, 100)])

PART 3

In [101]:
# 1. Standardize missing-value markers such as N/A, unknown, blank strings and - wherever appropriate.
missing_values = ["N/A", "n/a", "unknown", "Unknown", "-", ""]

df = df.replace(missing_values, 'nan')
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,NaN,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,NaN,not recorded,NaN
2,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,NaN,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,NaN,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [106]:
# 2. Remove unnecessary leading and trailing spaces from text columns.
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()
df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_25040\4105285026.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,NaN,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,NaN,not recorded,NaN
2,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,NaN,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,NaN,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [112]:
# 3. Standardize Gender values into consistent categories.
df["Gender"].str.strip().str.lower()

df["Gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,Male,NaN,SCIENCE,81,NaN,95,NaN,YES,NaN,good
1,S002,Neha Patel,Male,10th,English,105,3.5,80,Jodhpur,NaN,not recorded,NaN
2,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,Female,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,NaN,Yes,2026/09/15,Absent
119,S044,Priya Singh,Female,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,NaN,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [120]:
# 4. Standardize Subject names, such as Mathematics and math.
df["Subject"].str.strip().str.lower()

df["Subject"].replace({
    "math": "Mathematics",
    "maths": "Mathematics",
    "mathematics": "Mathematics",
    "english": "English",
    "science": "Science",
    "computer": "Computer Science",
    "computer science": "Computer Science"
})
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,Male,NaN,Science,81,NaN,95,NaN,YES,NaN,good
1,S002,Neha Patel,Male,10th,English,105,3.5,80,Jodhpur,NaN,not recorded,NaN
2,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,Female,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Mathematics,95,NaN,74,NaN,Yes,2026/09/15,Absent
119,S044,Priya Singh,Female,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,English,NaN,6,88,NaN,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,English,-5,6,74,sikar,Y,2026-09-15,Absent

In [124]:
# 5. Standardize City names with consistent capitalization.
df["City"] = df["City"].str.strip().str.title()
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,Male,NaN,Science,81,NaN,95,NaN,YES,NaN,good
1,S002,Neha Patel,Male,10th,English,105,3.5,80,Jodhpur,NaN,not recorded,NaN
2,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,Female,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,Jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Mathematics,95,NaN,74,NaN,Yes,2026/09/15,Absent
119,S044,Priya Singh,Female,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,NaN,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,English,NaN,6,88,NaN,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,English,-5,6,74,Sikar,Y,2026-09-15,Absent

In [126]:
# 6. Convert Attendance_%, Study_Hours_Per_Day and Exam_Score into numeric data types.
cols = ["Attendance_%", "Study_Hours_Per_Day", "Exam_Score"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[cols].dtypes)

Attendance_%           float64
Study_Hours_Per_Day    float64
Exam_Score             float64
dtype: object

In [130]:
# 7. Identify attendance values outside 0–100, negative study hours and exam scores outside 0–100.
print("Invalid attendance:")
print(df[~df["Attendance_%"].between(0, 100)])

print("Negative study hours:")
print(df[df["Study_Hours_Per_Day"] < 0])

print("Invalid exam scores:")
print(df[~df["Exam_Score"].between(0, 100)])

Invalid attendance:
    Student_ID  Student Name  Gender     Class           Subject  \
1         S002    Neha Patel    Male      10th           English
4         S092   Vikas Yadav    Male      12th  Computer Science
6         S062   Anjali Jain    Male        12       Mathematics
7         S026  Isha Agarwal  Female       Ten  Computer Science
8         S088     Arjun Rao  Female       Ten           English
13        S006     Arjun Rao  Female      10th           English
15        S062     Arjun Rao     NaN      10th           English
16        S058   Anjali Jain    Male        12  Computer Science
20        S090   Vikas Yadav    Male      10th           Science
23        S048  Isha Agarwal  Female        11           English
25        S054   Sneha Gupta  Female       Ten       Mathematics
26        S007   Sneha Gupta  Female        XI       Mathematics
27        S054  Pooja Kumari  Female        12           English
28        S064     Aman Khan  Female        10           Science
30        S067   Rohit Joshi  Female      10th       Mathematics
34        S086   Rohit Joshi    Male      10th  Computer Science
37        S062     Karan Das  Female      12th           English
40        S039     Karan Das  Female        XI           Science
41        S095   Rohit Joshi     NaN      12th           English
45        S036   Rahul Verma     NaN  Class 12           Science
50        S035   Vikas Yadav  Female        11               NaN
51        S046     Karan Das     NaN      12th               NaN
52        S065   Priya Singh     NaN  Class 10           Science
55        S033   Rohit Joshi  Female      10th  Computer Science
57        S016   Priya Singh     NaN        10       Mathematics
58        S008   Kavya Mehta    Male        11  Computer Science
60        S056     Arjun Rao    Male  Class 10       Mathematics
62        S055   Mohit Saini  Female        10       Mathematics
63        S037     Aman Khan  Female        12       Mathematics
65        S012   Rohit Joshi     NaN      12th       Mathematics
66        S103  Isha Agarwal     NaN        10           English
69        S023    Neha Patel  Female  Class 10           English
71        S070   Rahul Verma  Female        11       Mathematics
72        S047  Pooja Kumari     NaN  Class 10       Mathematics
75        S039   Anjali Jain    Male      10th       Mathematics
80        S094    Neha Patel    Male  Class 10           Science
81        S070  Isha Agarwal     NaN  Class 10  Computer Science
83        S005  Isha Agarwal    Male      10th       Mathematics
85        S034   Rahul Verma  Female        11       Mathematics
87        S072   Mohit Saini     NaN        XI  Computer Science
89        S051    Neha Patel  Female  Class 12       Mathematics
91        S097  Aarav Sharma    Male        12       Mathematics
95        S041     Karan Das     NaN        10               NaN
97        S057   Rahul Verma    Male        11  Computer Science
99        S088   Mohit Saini  Female        12  Computer Science
104       S065  Pooja Kumari  Female  Class 12           English
105       S092   Rohit Joshi    Male        12  Computer Science
106       S048    Neha Patel    Male        XI           Science
109       S081   Priya Singh  Female      10th           Science
111       S037   Vikas Yadav    Male        12           Science
112       S025     Aman Khan     NaN        XI  Computer Science
114       S046     Aman Khan  Female      12th       Mathematics
116       S022  Aarav Sharma  Female       NaN       Mathematics
121       S088     Arjun Rao  Female       Ten           English
122       S062     Arjun Rao     NaN      10th           English

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
1           105.0                  3.5        80.0  Jodhpur              NaN
4             NaN                  0.0        72.0   Jaipur              NaN
6             NaN                  NaN        72.0  Jodhpur               no
7           105.0                  3.5       101.0      NaN              Yes
8             NaN                  6.0        88.0      NaN              NaN
13            NaN                  3.5         NaN    Sikar               no
15           -5.0                  6.0        74.0    Sikar                Y
16            NaN                  5.0        88.0    Sikar               no
20            NaN                  2.5        43.0    Sikar              YES
23            NaN                  NaN        95.0    Sikar              NaN
25            NaN                  3.5        72.0   Jaipur              YES
26          105.0                  5.0        80.0      NaN              YES
27           -5.0                 -2.0       -10.0    Sikar              NaN
28            NaN                  1.0        43.0    Sikar              Yes
30            NaN                  NaN       -10.0  Jodhpur              NaN
34            NaN                 -2.0         NaN  Jodhpur              Yes
37            NaN                  0.0         NaN    Delhi              NaN
40            NaN                  NaN         NaN    Delhi               no
41          105.0                  5.0        72.0   Jaipur               No
45            NaN                  0.0        72.0      NaN              Yes
50            NaN                  4.0         NaN    Delhi              NaN
51            NaN                  2.0       -10.0      NaN                Y
52          105.0                 -2.0        95.0      NaN                N
55            NaN                  2.0         NaN      NaN                N
57          105.0                 -2.0       -10.0    Sikar              NaN
58            NaN                  NaN        43.0  Jodhpur               No
60          105.0                  NaN        72.0  Jodhpur                N
62            NaN                  1.0        88.0    Delhi                N
63          105.0                  4.0       101.0    Delhi               No
65           -5.0                 -2.0        95.0   Jaipur              Yes
66          105.0                  0.0        72.0    Sikar                N
69          105.0                  3.5        74.0    Sikar              NaN
71            NaN                  NaN       -10.0    Delhi              Yes
72            NaN                  2.5         NaN  Jodhpur              Yes
75            NaN                  4.0       101.0  Jodhpur              Yes
80            NaN                  2.5        43.0  Jodhpur              NaN
81            NaN                  1.0         NaN    Delhi               No
83           -5.0                  3.5        80.0  Jodhpur              NaN
85          105.0                  6.0        74.0    Sikar               no
87            NaN                  NaN        72.0      NaN              NaN
89           -5.0                 -2.0        95.0      NaN              NaN
91            NaN                  0.0        74.0  Jodhpur                N
95            NaN                 -2.0        95.0      NaN                N
97          105.0                  NaN         NaN   Jaipur                Y
99            NaN                  4.0        43.0  Jodhpur              Yes
104           NaN                  3.5        67.0      NaN              Yes
105         105.0                  1.0        95.0    Sikar              NaN
106         105.0                 -2.0       101.0      NaN               No
109           NaN                 -2.0         NaN      NaN               No
111           NaN                  NaN        72.0      NaN              YES
112          -5.0                  3.5        88.0    Delhi                N
114           NaN                  0.0         NaN  Jodhpur              NaN
116          -5.0                  3.5        67.0      NaN                Y
121           NaN                  6.0        88.0      NaN              NaN
122          -5.0                  6.0        74.0    Sikar                Y

        Exam_Date            Remarks
1    not recorded                NaN
4    not recorded                NaN
6      2026-13-40          Excellent
7    not recorded    late submission
8      2026/09/15             Absent
13   not recorded               good
15     2026-09-15             Absent
16   not recorded                NaN
20     2026/09/15               good
23     2026/09/15               good
25            NaN    late submission
26     2026-09-15               Good
27     2026/09/15  Needs improvement
28     2026-09-15                NaN
30     2026-13-40          Excellent
34   not recorded                NaN
37     2026-09-15                NaN
40     2026-09-15                NaN
41     15/09/2026             Absent
45            NaN    late submission
50            NaN  Needs improvement
51     15/09/2026    late submission
52   not recorded               Good
55            NaN                NaN
57     2026-09-15          Excellent
58   not recorded  Needs improvement
60     15/09/2026                NaN
62   not recorded               Good
63     15/09/2026             Absent
65     2026-13-40                NaN
66   not recorded  Needs improvement
69     2026/09/15                NaN
71            NaN    late submission
72     2026-13-40          Excellent
75     2026-09-15                NaN
80     2026-13-40             Absent
81     2026-13-40               good
83     15/09/2026  Needs improvement
85     2026/09/15             Absent
87     2026-13-40             Absent
89     15/09/2026               good
91     2026-13-40               good
95     2026/09/15                NaN
97     15/09/2026    late submission
99     2026-09-15                NaN
104    2026/09/15          Excellent
105    15/09/2026             Absent
106    15/09/2026                NaN
109    2026-13-40          Excellent
111    2026-13-40  Needs improvement
112    15/09/2026                NaN
114    15/09/2026                NaN
116    2026-09-15               good
121    2026/09/15             Absent
122    2026-09-15             Absent
Negative study hours:
    Student_ID  Student Name  Gender     Class           Subject  \
27        S054  Pooja Kumari  Female        12           English
34        S086   Rohit Joshi    Male      10th  Computer Science
38        S001  Aarav Sharma     NaN      12th       Mathematics
52        S065   Priya Singh     NaN  Class 10           Science
53        S061     Karan Das  Female       Ten           Science
57        S016   Priya Singh     NaN        10       Mathematics
59        S033  Pooja Kumari  Female       Ten           Science
65        S012   Rohit Joshi     NaN      12th       Mathematics
78        S033   Sneha Gupta     NaN  Class 10  Computer Science
89        S051    Neha Patel  Female  Class 12       Mathematics
95        S041     Karan Das     NaN        10               NaN
96        S001  Aarav Sharma  Female        11               NaN
98        S082   Rahul Verma    Male       Ten               NaN
106       S048    Neha Patel    Male        XI           Science
109       S081   Priya Singh  Female      10th           Science

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
27           -5.0                 -2.0       -10.0    Sikar              NaN
34            NaN                 -2.0         NaN  Jodhpur              Yes
38           88.0                 -2.0         NaN      NaN              NaN
52          105.0                 -2.0        95.0      NaN                N
53           62.0                 -2.0         NaN    Sikar               no
57          105.0                 -2.0       -10.0    Sikar              NaN
59           78.0                 -2.0        88.0    Sikar                Y
65           -5.0                 -2.0        95.0   Jaipur              Yes
78           78.0                 -2.0       101.0    Sikar                Y
89           -5.0                 -2.0        95.0      NaN              NaN
95            NaN                 -2.0        95.0      NaN                N
96           62.0                 -2.0        67.0    Sikar              NaN
98           78.0                 -2.0        72.0      NaN              YES
106         105.0                 -2.0       101.0      NaN               No
109           NaN                 -2.0         NaN      NaN               No

        Exam_Date            Remarks
27     2026/09/15  Needs improvement
34   not recorded                NaN
38            NaN                NaN
52   not recorded               Good
53     2026-13-40                NaN
57     2026-09-15          Excellent
59   not recorded             Absent
65     2026-13-40                NaN
78     2026-13-40                NaN
89     15/09/2026               good
95     2026/09/15                NaN
96     2026-13-40                NaN
98     15/09/2026               Good
106    15/09/2026                NaN
109    2026-13-40          Excellent
Invalid exam scores:
    Student_ID  Student Name  Gender     Class           Subject  \
7         S026  Isha Agarwal  Female       Ten  Computer Science
9         S103  Aarav Sharma    Male      10th       Mathematics
11        S014  Aarav Sharma  Female        11       Mathematics
13        S006     Arjun Rao  Female      10th           English
18        S032   Rohit Joshi  Female        10       Mathematics
22        S060   Vikas Yadav    Male  Class 12               NaN
27        S054  Pooja Kumari  Female        12           English
29        S060   Kavya Mehta  Female       Ten           Science
30        S067   Rohit Joshi  Female      10th       Mathematics
34        S086   Rohit Joshi    Male      10th  Computer Science
35        S103     Karan Das    Male        11       Mathematics
36        S030  Isha Agarwal  Female  Class 12  Computer Science
37        S062     Karan Das  Female      12th           English
38        S001  Aarav Sharma     NaN      12th       Mathematics
39        S101     Karan Das  Female        12           English
40        S039     Karan Das  Female        XI           Science
47        S030    Neha Patel  Female        11       Mathematics
48        S076   Vikas Yadav    Male      10th       Mathematics
49        S085   Rahul Verma     NaN        11           Science
50        S035   Vikas Yadav  Female        11               NaN
51        S046     Karan Das     NaN      12th               NaN
53        S061     Karan Das  Female       Ten           Science
55        S033   Rohit Joshi  Female      10th  Computer Science
56        S099   Anjali Jain  Female        12           Science
57        S016   Priya Singh     NaN        10       Mathematics
63        S037     Aman Khan  Female        12       Mathematics
71        S070   Rahul Verma  Female        11       Mathematics
72        S047  Pooja Kumari     NaN  Class 10       Mathematics
75        S039   Anjali Jain    Male      10th       Mathematics
78        S033   Sneha Gupta     NaN  Class 10  Computer Science
81        S070  Isha Agarwal     NaN  Class 10  Computer Science
84        S009     Arjun Rao    Male  Class 10           Science
86        S085  Aarav Sharma    Male        12  Computer Science
90        S097     Karan Das  Female        XI           English
93        S038   Sneha Gupta    Male      12th           Science
97        S057   Rahul Verma    Male        11  Computer Science
106       S048    Neha Patel    Male        XI           Science
107       S002  Aarav Sharma  Female        11       Mathematics
108       S005   Mohit Saini     NaN  Class 10       Mathematics
109       S081   Priya Singh  Female      10th           Science
110       S066   Mohit Saini  Female        10       Mathematics
113       S098     Aman Khan     NaN        12           Science
114       S046     Aman Khan  Female      12th       Mathematics
115       S011   Mohit Saini  Female      10th           Science

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
7           105.0                  3.5       101.0      NaN              Yes
9            95.0                  2.5       101.0  Jodhpur               No
11           95.0                  0.0         NaN      NaN              NaN
13            NaN                  3.5         NaN    Sikar               no
18           76.0                  3.5       101.0  Jodhpur                N
22           76.0                  4.0         NaN  Jodhpur              Yes
27           -5.0                 -2.0       -10.0    Sikar              NaN
29           90.0                  2.0       101.0    Sikar              Yes
30            NaN                  NaN       -10.0  Jodhpur              NaN
34            NaN                 -2.0         NaN  Jodhpur              Yes
35           90.0                  0.0         NaN    Delhi               no
36           62.0                  3.5         NaN  Jodhpur              YES
37            NaN                  0.0         NaN    Delhi              NaN
38           88.0                 -2.0         NaN      NaN              NaN
39           76.0                  NaN         NaN    Sikar                N
40            NaN                  NaN         NaN    Delhi               no
47           81.0                  4.0         NaN    Sikar              Yes
48           62.0                  NaN         NaN    Sikar              Yes
49           76.0                  NaN         NaN   Jaipur               no
50            NaN                  4.0         NaN    Delhi              NaN
51            NaN                  2.0       -10.0      NaN                Y
53           62.0                 -2.0         NaN    Sikar               no
55            NaN                  2.0         NaN      NaN                N
56           78.0                  NaN       101.0   Jaipur              YES
57          105.0                 -2.0       -10.0    Sikar              NaN
63          105.0                  4.0       101.0    Delhi               No
71            NaN                  NaN       -10.0    Delhi              Yes
72            NaN                  2.5         NaN  Jodhpur              Yes
75            NaN                  4.0       101.0  Jodhpur              Yes
78           78.0                 -2.0       101.0    Sikar                Y
81            NaN                  1.0         NaN    Delhi               No
84           95.0                  0.0         NaN    Sikar              YES
86           78.0                  NaN       101.0    Sikar                Y
90           78.0                  5.0       -10.0    Sikar                Y
93           62.0                  2.5         NaN      NaN                N
97          105.0                  NaN         NaN   Jaipur                Y
106         105.0                 -2.0       101.0      NaN               No
107          76.0                  5.0         NaN   Jaipur              Yes
108          81.0                  4.0         NaN   Jaipur                Y
109           NaN                 -2.0         NaN      NaN               No
110          76.0                  2.0         NaN      NaN                Y
113          78.0                  NaN       -10.0      NaN               no
114           NaN                  0.0         NaN  Jodhpur              NaN
115          62.0                  1.0         NaN    Delhi              NaN

        Exam_Date            Remarks
7    not recorded    late submission
9      2026-09-15                NaN
11     2026/09/15    late submission
13   not recorded               good
18   not recorded                NaN
22     15/09/2026               Good
27     2026/09/15  Needs improvement
29   not recorded                NaN
30     2026-13-40          Excellent
34   not recorded                NaN
35     2026-13-40               good
36     2026-09-15          Excellent
37     2026-09-15                NaN
38            NaN                NaN
39     2026-09-15                NaN
40     2026-09-15                NaN

In [ ]:
# 2nd method
print(df[df["Attendance_%"].notna() & df["Attendance_%"].between(0, 100)])

print(df[df["Study_Hours_Per_Day"].notna() & (df["Study_Hours_Per_Day"] < 0)])

print(df[df["Exam_Score"].notna() & df["Exam_Score"].between(0, 100)])

    Student_ID  Student Name  Gender Class           Subject  Attendance_%  \
0         S075   Rohit Joshi    Male   NaN           Science          81.0
2         S092  Aarav Sharma     NaN    12  Computer Science          95.0
3         S021  Pooja Kumari  Female    XI  Computer Science          76.0
5         S002  Pooja Kumari    Male  10th       Mathematics          62.0
9         S103  Aarav Sharma    Male  10th       Mathematics          95.0
..         ...           ...     ...   ...               ...           ...
115       S011   Mohit Saini  Female  10th           Science          62.0
117       S073     Karan Das    Male  10th       Mathematics          62.0
118       S042   Vikas Yadav     NaN   NaN       Mathematics          95.0
119       S044   Priya Singh  Female  10th           English          88.0
120       S092  Aarav Sharma     NaN    12  Computer Science          95.0

     Study_Hours_Per_Day  Exam_Score     City Parent_Contacted   Exam_Date  \
0                    NaN        95.0      NaN              YES         NaN
2                    2.5        74.0  Jodhpur               no  2026-13-40
3                    0.0        95.0      NaN              Yes  15/09/2026
5                    3.5        80.0   Jaipur                N  2026-13-40
9                    2.5       101.0  Jodhpur               No  2026-09-15
..                   ...         ...      ...              ...         ...
115                  1.0         NaN    Delhi              NaN  2026/09/15
117                  2.5        88.0   Jaipur               No  15/09/2026
118                  NaN        74.0      NaN              Yes  2026/09/15
119                  NaN        95.0    Delhi              YES  2026/09/15
120                  2.5        74.0  Jodhpur               no  2026-13-40

    Remarks
0      good
2    Absent
3      good
5       NaN
9       NaN
..      ...
115    good
117     NaN
118  Absent
119    Good
120  Absent

[68 rows x 12 columns]
    Student_ID  Student Name  Gender     Class           Subject  \
27        S054  Pooja Kumari  Female        12           English
34        S086   Rohit Joshi    Male      10th  Computer Science
38        S001  Aarav Sharma     NaN      12th       Mathematics
52        S065   Priya Singh     NaN  Class 10           Science
53        S061     Karan Das  Female       Ten           Science
57        S016   Priya Singh     NaN        10       Mathematics
59        S033  Pooja Kumari  Female       Ten           Science
65        S012   Rohit Joshi     NaN      12th       Mathematics
78        S033   Sneha Gupta     NaN  Class 10  Computer Science
89        S051    Neha Patel  Female  Class 12       Mathematics
95        S041     Karan Das     NaN        10               NaN
96        S001  Aarav Sharma  Female        11               NaN
98        S082   Rahul Verma    Male       Ten               NaN
106       S048    Neha Patel    Male        XI           Science
109       S081   Priya Singh  Female      10th           Science

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
27           -5.0                 -2.0       -10.0    Sikar              NaN
34            NaN                 -2.0         NaN  Jodhpur              Yes
38           88.0                 -2.0         NaN      NaN              NaN
52          105.0                 -2.0        95.0      NaN                N
53           62.0                 -2.0         NaN    Sikar               no
57          105.0                 -2.0       -10.0    Sikar              NaN
59           78.0                 -2.0        88.0    Sikar                Y
65           -5.0                 -2.0        95.0   Jaipur              Yes
78           78.0                 -2.0       101.0    Sikar                Y
89           -5.0                 -2.0        95.0      NaN              NaN
95            NaN                 -2.0        95.0      NaN                N
96           62.0                 -2.0        67.0    Sikar              NaN
98           78.0                 -2.0        72.0      NaN              YES
106         105.0                 -2.0       101.0      NaN               No
109           NaN                 -2.0         NaN      NaN               No

        Exam_Date            Remarks
27     2026/09/15  Needs improvement
34   not recorded                NaN
38            NaN                NaN
52   not recorded               Good
53     2026-13-40                NaN
57     2026-09-15          Excellent
59   not recorded             Absent
65     2026-13-40                NaN
78     2026-13-40                NaN
89     15/09/2026               good
95     2026/09/15                NaN
96     2026-13-40                NaN
98     15/09/2026               Good
106    15/09/2026                NaN
109    2026-13-40          Excellent
    Student_ID  Student Name  Gender Class           Subject  Attendance_%  \
0         S075   Rohit Joshi    Male   NaN           Science          81.0
1         S002    Neha Patel    Male  10th           English         105.0
2         S092  Aarav Sharma     NaN    12  Computer Science          95.0
3         S021  Pooja Kumari  Female    XI  Computer Science          76.0
4         S092   Vikas Yadav    Male  12th  Computer Science           NaN
..         ...           ...     ...   ...               ...           ...
118       S042   Vikas Yadav     NaN   NaN       Mathematics          95.0
119       S044   Priya Singh  Female  10th           English          88.0
120       S092  Aarav Sharma     NaN    12  Computer Science          95.0
121       S088     Arjun Rao  Female   Ten           English           NaN
122       S062     Arjun Rao     NaN  10th           English          -5.0

     Study_Hours_Per_Day  Exam_Score     City Parent_Contacted     Exam_Date  \
0                    NaN        95.0      NaN              YES           NaN
1                    3.5        80.0  Jodhpur              NaN  not recorded
2                    2.5        74.0  Jodhpur               no    2026-13-40
3                    0.0        95.0      NaN              Yes    15/09/2026
4                    0.0        72.0   Jaipur              NaN  not recorded
..                   ...         ...      ...              ...           ...
118                  NaN        74.0      NaN              Yes    2026/09/15
119                  NaN        95.0    Delhi              YES    2026/09/15
120                  2.5        74.0  Jodhpur               no    2026-13-40
121                  6.0        88.0      NaN              NaN    2026/09/15
122                  6.0        74.0    Sikar                Y    2026-09-15

    Remarks
0      good
1       NaN
2    Absent
3      good
4       NaN
..      ...
118  Absent
119    Good
120  Absent
121  Absent
122  Absent

[79 rows x 12 columns]

In [137]:
# 8. Handle invalid numerical values using a clearly stated rule.
df.loc[~df["Attendance_%"].between(0, 100), "Attendance_%"]

df.loc[df["Study_Hours_Per_Day"] < 0, "Study_Hours_Per_Day"]

df.loc[~df["Exam_Score"].between(0, 100), "Exam_Score"]

7     NaN
9     NaN
11    NaN
13    NaN
18    NaN
22    NaN
27    NaN
29    NaN
30    NaN
34    NaN
35    NaN
36    NaN
37    NaN
38    NaN
39    NaN
40    NaN
47    NaN
48    NaN
49    NaN
50    NaN
51    NaN
53    NaN
55    NaN
56    NaN
57    NaN
63    NaN
71    NaN
72    NaN
75    NaN
78    NaN
81    NaN
84    NaN
86    NaN
90    NaN
93    NaN
97    NaN
106   NaN
107   NaN
108   NaN
109   NaN
110   NaN
113   NaN
114   NaN
115   NaN
Name: Exam_Score, dtype: float64

In [139]:
# 9. Remove exact duplicate rows, but do not automatically remove every repeated Student_ID.
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (120, 12)
After: (120, 12)

In [141]:
# 10. Convert Exam_Date into a proper datetime data type and identify invalid dates.
df["Exam_Date"] = pd.to_datetime(df["Exam_Date"], errors="coerce")

print(df[df["Exam_Date"].isna()])

    Student_ID  Student Name  Gender     Class           Subject  \
0         S075   Rohit Joshi    Male       NaN           Science
1         S002    Neha Patel    Male      10th           English
2         S092  Aarav Sharma     NaN        12  Computer Science
4         S092   Vikas Yadav    Male      12th  Computer Science
5         S002  Pooja Kumari    Male      10th       Mathematics
..         ...           ...     ...       ...               ...
107       S002  Aarav Sharma  Female        11       Mathematics
108       S005   Mohit Saini     NaN  Class 10       Mathematics
109       S081   Priya Singh  Female      10th           Science
111       S037   Vikas Yadav    Male        12           Science
113       S098     Aman Khan     NaN        12           Science

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
0            81.0                  NaN        95.0      NaN              YES
1             NaN                  3.5        80.0  Jodhpur              NaN
2            95.0                  2.5        74.0  Jodhpur               no
4             NaN                  0.0        72.0   Jaipur              NaN
5            62.0                  3.5        80.0   Jaipur                N
..            ...                  ...         ...      ...              ...
107          76.0                  5.0         NaN   Jaipur              Yes
108          81.0                  4.0         NaN   Jaipur                Y
109           NaN                  NaN         NaN      NaN               No
111           NaN                  NaN        72.0      NaN              YES
113          78.0                  NaN         NaN      NaN               no

    Exam_Date            Remarks
0         NaT               good
1         NaT                NaN
2         NaT             Absent
4         NaT                NaN
5         NaT                NaN
..        ...                ...
107       NaT               good
108       NaT    late submission
109       NaT          Excellent
111       NaT  Needs improvement
113       NaT    late submission

[66 rows x 12 columns]

In [143]:
# 11. Handle missing numerical and categorical values using suitable strategies.
# Numerical input features ko median se fill karo
numeric_features = ["Attendance_%", "Study_Hours_Per_Day"]

for col in numeric_features:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns mein missing values ko Unknown banao
categorical_cols = [
    "Gender", "Class", "Subject", "City", "Parent_Contacted"
]

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

# Exam_Score aur Exam_Date ko filhaal missing rehne do
print(df.isnull().sum())

Student_ID              0
Student Name            0
Gender                  0
Class                   0
Subject                 0
Attendance_%            0
Study_Hours_Per_Day     0
Exam_Score             44
City                    0
Parent_Contacted        0
Exam_Date              66
Remarks                41
dtype: int64

PART 4

In [145]:
# 1. Calculate the mean, median, minimum and maximum exam score.
print("Mean:", df["Exam_Score"].mean())
print("Median:", df["Exam_Score"].median())
print("Minimum:", df["Exam_Score"].min())
print("Maximum:", df["Exam_Score"].max())

Mean: 76.35526315789474
Median: 74.0
Minimum: 43.0
Maximum: 95.0

In [147]:
# 2. Find the average attendance percentage
print("Average Attendance:", df["Attendance_%"].mean())

Average Attendance: 81.16666666666667

In [149]:
# 3. Display records of students whose exam score is greater than or equal to 70.
print(df[df["Exam_Score"] >= 70])

    Student_ID  Student Name   Gender     Class           Subject  \
0         S075   Rohit Joshi     Male   Unknown           Science
1         S002    Neha Patel     Male      10th           English
2         S092  Aarav Sharma  Unknown        12  Computer Science
3         S021  Pooja Kumari   Female        XI  Computer Science
4         S092   Vikas Yadav     Male      12th  Computer Science
5         S002  Pooja Kumari     Male      10th       Mathematics
6         S062   Anjali Jain     Male        12       Mathematics
8         S088     Arjun Rao   Female       Ten           English
10        S099   Vikas Yadav     Male  Class 10       Mathematics
14        S027  Isha Agarwal  Unknown  Class 12  Computer Science
15        S062     Arjun Rao  Unknown      10th           English
16        S058   Anjali Jain     Male        12  Computer Science
17        S002   Priya Singh   Female        10           Science
21        S001   Rohit Joshi     Male       Ten       Mathematics
23        S048  Isha Agarwal   Female        11           English
24        S072    Neha Patel     Male   Unknown       Mathematics
25        S054   Sneha Gupta   Female       Ten       Mathematics
26        S007   Sneha Gupta   Female        XI       Mathematics
31        S017   Priya Singh     Male  Class 12       Mathematics
32        S025   Mohit Saini     Male  Class 12           Unknown
33        S015   Vikas Yadav     Male        XI       Mathematics
41        S095   Rohit Joshi  Unknown      12th           English
43        S012    Neha Patel     Male      10th       Mathematics
45        S036   Rahul Verma  Unknown  Class 12           Science
46        S036   Sneha Gupta  Unknown        11  Computer Science
52        S065   Priya Singh  Unknown  Class 10           Science
54        S020   Mohit Saini  Unknown      12th       Mathematics
59        S033  Pooja Kumari   Female       Ten           Science
60        S056     Arjun Rao     Male  Class 10       Mathematics
61        S026   Rohit Joshi     Male        10           English
62        S055   Mohit Saini   Female        10       Mathematics
64        S104  Aarav Sharma   Female       Ten       Mathematics
65        S012   Rohit Joshi  Unknown      12th       Mathematics
66        S103  Isha Agarwal  Unknown        10           English
67        S038   Kavya Mehta     Male  Class 10       Mathematics
68        S074   Anjali Jain   Female        10           Science
69        S023    Neha Patel   Female  Class 10           English
70        S027    Neha Patel     Male   Unknown           Science
73        S052  Isha Agarwal   Female      12th           Science
74        S003  Isha Agarwal     Male  Class 10           Unknown
77        S042     Karan Das     Male        12       Mathematics
82        S014   Rahul Verma     Male        10           Science
83        S005  Isha Agarwal     Male      10th       Mathematics
85        S034   Rahul Verma   Female        11       Mathematics
87        S072   Mohit Saini  Unknown        XI  Computer Science
88        S066     Arjun Rao     Male        10           English
89        S051    Neha Patel   Female  Class 12       Mathematics
91        S097  Aarav Sharma     Male        12       Mathematics
94        S068  Isha Agarwal     Male       Ten       Mathematics
95        S041     Karan Das  Unknown        10           Unknown
98        S082   Rahul Verma     Male       Ten           Unknown
101       S083  Pooja Kumari     Male        10           English
102       S092     Arjun Rao     Male      10th       Mathematics
103       S074   Rahul Verma     Male        10  Computer Science
105       S092   Rohit Joshi     Male        12  Computer Science
111       S037   Vikas Yadav     Male        12           Science
112       S025     Aman Khan  Unknown        XI  Computer Science
117       S073     Karan Das     Male      10th       Mathematics
118       S042   Vikas Yadav  Unknown   Unknown       Mathematics
119       S044   Priya Singh   Female      10th           English

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
0            81.0                  3.5        95.0  Unknown              YES
1            81.0                  3.5        80.0  Jodhpur          Unknown
2            95.0                  2.5        74.0  Jodhpur               no
3            76.0                  0.0        95.0  Unknown              Yes
4            81.0                  0.0        72.0   Jaipur          Unknown
5            62.0                  3.5        80.0   Jaipur                N
6            81.0                  3.5        72.0  Jodhpur               no
8            81.0                  6.0        88.0  Unknown          Unknown
10           81.0                  4.0        80.0    Delhi               no
14           81.0                  2.0        88.0    Sikar                N
15           81.0                  6.0        74.0    Sikar                Y
16           81.0                  5.0        88.0    Sikar               no
17           95.0                  6.0        88.0    Sikar               No
21           90.0                  4.0        72.0  Unknown              YES
23           81.0                  3.5        95.0    Sikar          Unknown
24           90.0                  5.0        74.0    Sikar               no
25           81.0                  3.5        72.0   Jaipur              YES
26           81.0                  5.0        80.0  Unknown              YES
31           78.0                  3.5        72.0  Jodhpur          Unknown
32           81.0                  3.5        95.0   Jaipur          Unknown
33           90.0                  3.5        95.0  Unknown               no
41           81.0                  5.0        72.0   Jaipur               No
43           95.0                  1.0        74.0    Delhi              YES
45           81.0                  0.0        72.0  Unknown              Yes
46           90.0                  1.0        88.0    Sikar               No
52           81.0                  3.5        95.0  Unknown                N
54           81.0                  1.0        72.0  Jodhpur               no
59           78.0                  3.5        88.0    Sikar                Y
60           81.0                  3.5        72.0  Jodhpur                N
61           95.0                  3.5        88.0    Delhi          Unknown
62           81.0                  1.0        88.0    Delhi                N
64           76.0                  5.0        88.0    Sikar          Unknown
65           81.0                  3.5        95.0   Jaipur              Yes
66           81.0                  0.0        72.0    Sikar                N
67           78.0                  1.0        72.0   Jaipur              Yes
68           62.0                  3.5        80.0    Sikar              Yes
69           81.0                  3.5        74.0    Sikar          Unknown
70           90.0                  3.5        95.0    Sikar                Y
73           95.0                  6.0        88.0    Sikar          Unknown
74           78.0                  6.0        95.0  Unknown          Unknown
77           90.0                  6.0        88.0    Sikar              Yes
82           95.0                  3.5        88.0  Jodhpur          Unknown
83           81.0                  3.5        80.0  Jodhpur          Unknown
85           81.0                  6.0        74.0    Sikar               no
87           81.0                  3.5        72.0  Unknown          Unknown
88           95.0                  3.5        88.0    Sikar                N
89           81.0                  3.5        95.0  Unknown          Unknown
91           81.0                  0.0        74.0  Jodhpur                N
94           90.0                  3.5        74.0   Jaipur                Y
95           81.0                  3.5        95.0  Unknown                N
98           78.0                  3.5        72.0  Unknown              YES
101          95.0                  4.0        95.0  Unknown                N
102          95.0                  1.0        72.0   Jaipur              Yes
103          81.0                  4.0        95.0  Jodhpur              YES
105          81.0                  1.0        95.0    Sikar          Unknown
111          81.0                  3.5        72.0  Unknown              YES
112          81.0                  3.5        88.0    Delhi                N
117          62.0                  2.5        88.0   Jaipur               No
118          95.0                  3.5        74.0  Unknown              Yes
119          88.0                  3.5        95.0    Delhi              YES

     Exam_Date            Remarks
0          NaT               good
1          NaT                NaN
2          NaT             Absent
3   2026-09-15               good
4          NaT                NaN
5          NaT                NaN
6          NaT          Excellent
8   2026-09-15             Absent
10         NaT             Absent
14  2026-09-15               good
15  2026-09-15             Absent
16         NaT                NaN
17         NaT                NaN
21         NaT    late submission
23  2026-09-15               good
24         NaT          Excellent
25         NaT    late submission
26  2026-09-15               Good
31  2026-09-15    late submission
32         NaT                NaN
33  2026-09-15  Needs improvement
41  2026-09-15             Absent
43  2026-09-15               Good
45         NaT    late submission
46  2026-09-15                NaN
52         NaT               Good
54         NaT    late submission
59         NaT             Absent
60  2026-09-15                NaN
61  2026-09-15                NaN
62         NaT               Good
64  2026-09-15          Excellent
65         NaT                NaN
66         NaT  Needs improvement
67         NaT                NaN
68         NaT               good
69  2026-09-15                NaN
70  2026-09-15             Absent
73         NaT                NaN
74         NaT  Needs improvement
77         NaT                NaN
82         NaT                NaN
83  2026-09-15  Needs improvement
85  2026-09-15             Absent
87         NaT             Absent
88         NaT          Excellent
89  2026-09-15               good
91         NaT               good
94         NaT          Excellent
95  2026-09-15                NaN
98  2026-09-15               Good
101        NaT               Good
102 2026-09-15                NaN
103        NaT  Needs improvement
105 2026-09-15             Absent
111        NaT  Needs improvement
112 2026-09-15                NaN
117 2026-09-15                NaN
118 2026-09-15             Absent
119 2026-09-15               Good

In [151]:
# 4. Find the average exam score for each subject.
print(df.groupby("Subject")["Exam_Score"].mean())

Subject
Computer Science    75.692308
English             79.307692
Mathematics         74.666667
Science             74.933333
Unknown             84.800000
Name: Exam_Score, dtype: float64

In [153]:
# 5. Find the average exam score for each class.
print(df.groupby("Class")["Exam_Score"].mean())

Class
10          80.250000
10th        76.222222
11          68.333333
12          75.750000
12th        73.666667
Class 10    74.750000
Class 12    79.428571
Ten         74.625000
Unknown     78.666667
XI          78.833333
Name: Exam_Score, dtype: float64

In [155]:
# 6. Count records belonging to each subject and gender.
print(df["Subject"].value_counts())
print(df["Gender"].value_counts())

Subject
Mathematics         47
Science             26
Computer Science    21
English             18
Unknown              8
Name: count, dtype: int64
Gender
Male       49
Female     45
Unknown    26
Name: count, dtype: int64

In [157]:
# 7. Find the highest and lowest recorded exam scores.
print("Highest Score:", df["Exam_Score"].max())
print("Lowest Score:", df["Exam_Score"].min())

Highest Score: 95.0
Lowest Score: 43.0

In [159]:
# 8. Sort records by Exam_Score in descending order.
sorted_df = df.sort_values("Exam_Score", ascending=False)

print(sorted_df)

    Student_ID  Student Name   Gender    Class           Subject  \
0         S075   Rohit Joshi     Male  Unknown           Science
3         S021  Pooja Kumari   Female       XI  Computer Science
101       S083  Pooja Kumari     Male       10           English
95        S041     Karan Das  Unknown       10           Unknown
70        S027    Neha Patel     Male  Unknown           Science
..         ...           ...      ...      ...               ...
109       S081   Priya Singh   Female     10th           Science
110       S066   Mohit Saini   Female       10       Mathematics
113       S098     Aman Khan  Unknown       12           Science
114       S046     Aman Khan   Female     12th       Mathematics
115       S011   Mohit Saini   Female     10th           Science

     Attendance_%  Study_Hours_Per_Day  Exam_Score     City Parent_Contacted  \
0            81.0                  3.5        95.0  Unknown              YES
3            76.0                  0.0        95.0  Unknown              Yes
101          95.0                  4.0        95.0  Unknown                N
95           81.0                  3.5        95.0  Unknown                N
70           90.0                  3.5        95.0    Sikar                Y
..            ...                  ...         ...      ...              ...
109          81.0                  3.5         NaN  Unknown               No
110          76.0                  2.0         NaN  Unknown                Y
113          78.0                  3.5         NaN  Unknown               no
114          81.0                  0.0         NaN  Jodhpur          Unknown
115          62.0                  1.0         NaN    Delhi          Unknown

     Exam_Date          Remarks
0          NaT             good
3   2026-09-15             good
101        NaT             Good
95  2026-09-15              NaN
70  2026-09-15           Absent
..         ...              ...
109        NaT        Excellent
110 2026-09-15              NaN
113        NaT  late submission
114 2026-09-15              NaN
115 2026-09-15             good

[120 rows x 12 columns]

In [161]:
# 9. Create a new column named Performance_Level using a rule you define and document.
conditions = [
    df["Exam_Score"] >= 80,
    df["Exam_Score"] >= 70,
    df["Exam_Score"] >= 50,
    df["Exam_Score"] < 50
]

labels = [
    "Excellent",
    "Good",
    "Average",
    "Needs Improvement"
]

df["Performance_Level"] = np.select(
    conditions,
    labels,
    default="Unknown"
)

print(df[["Exam_Score", "Performance_Level"]].head(10))

   Exam_Score Performance_Level
0        95.0         Excellent
1        80.0         Excellent
2        74.0              Good
3        95.0         Excellent
4        72.0              Good
5        80.0         Excellent
6        72.0              Good
7         NaN           Unknown
8        88.0         Excellent
9         NaN           Unknown

In [163]:
# 10. Calculate the correlation between attendance and exam score.
print(df["Attendance_%"].corr(df["Exam_Score"]))

0.1329420960157523

PART 5 --> EXPORT ML AND CONNECTION

In [166]:
# 1. Export the cleaned DataFrame to cleaned_student_performance.csv without saving the index.
df.to_csv("cleaned_student_performance.csv", index=False)
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks,Performance_Level
0,S075,Rohit Joshi,Male,Unknown,Science,81.0,3.5,95.0,Unknown,YES,NaT,good,Excellent
1,S002,Neha Patel,Male,10th,English,81.0,3.5,80.0,Jodhpur,Unknown,NaT,NaN,Excellent
2,S092,Aarav Sharma,Unknown,12,Computer Science,95.0,2.5,74.0,Jodhpur,no,NaT,Absent,Good
3,S021,Pooja Kumari,Female,XI,Computer Science,76.0,0.0,95.0,Unknown,Yes,2026-09-15,good,Excellent
4,S092,Vikas Yadav,Male,12th,Computer Science,81.0,0.0,72.0,Jaipur,Unknown,NaT,NaN,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S011,Mohit Saini,Female,10th,Science,62.0,1.0,NaN,Delhi,Unknown,2026-09-15,good,Unknown
116,S022,Aarav Sharma,Female,Unknown,Mathematics,81.0,3.5,67.0,Unknown,Y,2026-09-15,good,Average
117,S073,Karan Das,Male,10th,Mathematics,62.0,2.5,88.0,Jaipur,No,2026-09-15,NaN,Excellent
118,S042,Vikas Yadav,Unknown,Unknown,Mathematics,95.0,3.5,74.0,Unknown,Yes,2026-09-15,Absent,Good
119,S044,Priya Singh,Female,10th,English,88.0,3.5,95.0,Delhi,YES,2026-09-15,Good,Excellent

In [168]:
# 2. Reload the exported CSV and verify its shape and data types.
df_check = pd.read_csv("cleaned_student_performance.csv")

print("Shape:", df_check.shape)
print(df_check.dtypes)
print(df_check.head())

Shape: (120, 13)
Student_ID                 str
Student Name               str
Gender                     str
Class                      str
Subject                    str
Attendance_%           float64
Study_Hours_Per_Day    float64
Exam_Score             float64
City                       str
Parent_Contacted           str
Exam_Date                  str
Remarks                    str
Performance_Level          str
dtype: object
  Student_ID  Student Name   Gender    Class           Subject  Attendance_%  \
0       S075   Rohit Joshi     Male  Unknown           Science          81.0
1       S002    Neha Patel     Male     10th           English          81.0
2       S092  Aarav Sharma  Unknown       12  Computer Science          95.0
3       S021  Pooja Kumari   Female       XI  Computer Science          76.0
4       S092   Vikas Yadav     Male     12th  Computer Science          81.0

   Study_Hours_Per_Day  Exam_Score     City Parent_Contacted   Exam_Date  \
0                  3.5        95.0  Unknown              YES         NaN
1                  3.5        80.0  Jodhpur          Unknown         NaN
2                  2.5        74.0  Jodhpur               no         NaN
3                  0.0        95.0  Unknown              Yes  2026-09-15
4                  0.0        72.0   Jaipur          Unknown         NaN

  Remarks Performance_Level
0    good         Excellent
1     NaN         Excellent
2  Absent              Good
3    good         Excellent
4     NaN              Good

In [169]:
# # 3. Write five observations from your analysis.
# 1. Dataset ka average exam score mean() se pata chalta hai.
# 2. Average attendance Attendance_% ke mean se pata chalti hai.
# 3. Sabse zyada average score wala subject identify kiya ja sakta hai.
# 4. Sabse zyada average score wali class identify ki ja sakti hai.
# 5. Attendance aur exam score ke correlation se unke linear relationship ka idea milta hai.

In [174]:
# 4. Identify possible input features (X) for predicting exam scores.
X = df[
    [
        "Gender",
        "Class",
        "Subject",
        "Attendance_%",
        "Study_Hours_Per_Day"
    ]
]

print(X.head())
#Categorical features ko ML model mein use karne se pehle encoding karni hogi, jaise one-hot encoding.

    Gender    Class           Subject  Attendance_%  Study_Hours_Per_Day
0     Male  Unknown           Science          81.0                  3.5
1     Male     10th           English          81.0                  3.5
2  Unknown       12  Computer Science          95.0                  2.5
3   Female       XI  Computer Science          76.0                  0.0
4     Male     12th  Computer Science          81.0                  0.0

In [ ]:
# 5. Identify the target variable (y) and explain why it is the target.
y = df["Exam_Score"]

print(y.head())
#Target Exam_Score hai, kyunki model ka purpose students ke exam scores predict karna hai.

0    95.0
1    80.0
2    74.0
3    95.0
4    72.0
Name: Exam_Score, dtype: float64

In [ ]:
# 6. Explain two data-quality problems that should be addressed before training an ML model.
# Problem 1: Missing aur invalid values
# Attendance 105 ho sakti hai, study hours mein unknown ho sakta hai, ya exam score missing ho sakta hai. Inhein handle kiye bina model ko galat ya incomplete data mil sakta hai.
# Problem 2: Inconsistent categories aur duplicate records
# math, Maths, aur Mathematics ek hi subject ko represent kar sakte hain. Exact duplicates bhi kuch records ko zyada weight de sakte hain. Inhein clean karna zaroori hai.